# import = [
#     "~/.config/alacritty/themes/themes/ayu_dark.toml"
# ]

[shell]
program = "/home/luasantilli/.nix-profile/bin/nu"
args = [""]
# program = "~/.nix-profile/bin/zellij"
# args = ["options", "--default-shell", "nu"]
# [shell]
# program = "~./"
#   program: ~/.cargo/bin/zellij
#   args:
#     - options
#     - --default-shell
#     - nu

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Fullscreen"
padding.x = 0
padding.y = 0

# Default colors
[colors.primary]
background = '#111111'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

# Bright colors
[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
